# Generated by Django 6.0.4 on 2026-04-15 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('user_id', models.IntegerField(db_index=True)),
                ('user_username', models.CharField(default='anonymous', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('image_file', models.ImageField(upload_to='gallery/images/%Y/%m/%d/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='gallery/thumbnails/%Y/%m/%d/')),
                ('user_id', models.IntegerField(db_index=True)),
                ('user_username', models.CharField(default='anonymous', max_length=150)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending Verification'), ('unedited', 'Unedited (Authentic)'), ('edited', 'Edited (Modified)'), ('rejected', 'Rejected'), ('error', 'Verification Error')], db_index=True, default='pending', max_length=20)),
                ('ai_confidence_score', models.FloatField(blank=True, null=True)),
                ('ai_report', models.JSONField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_filename', models.CharField(max_length=500)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('mime_type', models.CharField(max_length=100)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='GalleryImage.album')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ImageVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('unedited', 'Unedited (Authentic)'), ('edited', 'Edited (Modified)'), ('rejected', 'Rejected'), ('error', 'Verification Error')], max_length=20)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('ai_response', models.JSONField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='GalleryImage.image')),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['user_id', 'verification_status'], name='GalleryImag_user_id_087d44_idx'),
        ),
    ]
