# Generated by Django 6.0.4 on 2026-04-17 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GalleryImage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AddField(
            model_name='album',
            name='cover_image',
            field=models.ForeignKey(blank=True, help_text='Image used as album cover', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cover_of_albums', to='GalleryImage.image'),
        ),
        migrations.AddField(
            model_name='image',
            name='is_favorite',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('user_id', models.IntegerField(db_index=True)),
                ('color', models.CharField(default='#adc6ff', help_text='Hex color for display (e.g., #adc6ff)', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'user_id')},
            },
        ),
        migrations.AddField(
            model_name='image',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='images', to='GalleryImage.tag'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['user_id', 'is_favorite'], name='GalleryImag_user_id_ae62dd_idx'),
        ),
    ]
