# Generated by Django 6.0.4 on 2026-04-17 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True, help_text='ID of the user who performed the action.')),
                ('action', models.CharField(choices=[('image_uploaded', 'Image Uploaded'), ('image_deleted', 'Image Deleted'), ('image_verified', 'Image Verified'), ('user_login', 'User Login'), ('user_logout', 'User Logout'), ('user_registered', 'User Registered'), ('other', 'Other')], db_index=True, default='other', max_length=50)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Additional context (image_id, title, status, etc.)')),
                ('service', models.CharField(default='unknown', help_text='The microservice that generated this log entry.', max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Action Log',
                'verbose_name_plural': 'Action Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
